config/routes.rb
YACMS::Application.routes.draw do
  namespace :admin do
    resources :pages do
      collection do
        post :rebuild
        post :add_image
        post :add_file
        post :add_snippet
      end
    end
    resources :posts do
      collection do
        post :add_image
        post :add_file
        post :add_snippet
      end
    end
    resources :images, except: :show
    resources :attachments, except: :show
    resources :snippets
    resources :users, except: [:show, :new, :create]
    resources :settings, only: [:edit, :update]
  end

  resources :pages, only: [:show]
  resources :posts, only: [:index, :show] do
    resources :comments, only: [:new, :create]
  end

  devise_for :users

  root to: 'pages#home'
end

app/views/admin/pages/_form.html.slim
= render 'shared/select_image', add_path: add_image_admin_pages_path, ckeditor_id: 'page_body'
= simple_form_for(page_form_values(@page), :html => { class: 'form-horizontal' }) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :title
    = f.input :parent_id do
      = f.select :parent_id, nested_options(Page.all, :selected => @page.parent),
                 {include_blank: true}, {class: :nested_options}
    = link_to 'Add image', '#', class: 'show_select_images_popup btn'
    = select_tag '', options_for_select(Attachment.accessible_by(current_ability).map{ |f| [f.name, f.id] }),
                 id: 'select_file'
    = link_to 'Add file', add_file_admin_pages_path, class: 'add_file btn', data: {ckeditor_id: 'page_body'}
    = select_tag '', options_for_select(Snippet.accessible_by(current_ability).map{ |s| [s.name, s.id] }),
                 id: 'select_snippet'
    = link_to 'Add snippet', add_snippet_admin_pages_path, class: 'add_snippet btn', data: {ckeditor_id: 'page_body'}
    = f.input :body, as: :ckeditor, :ckeditor => {"toolbar" => "Basic"}
    = f.input :show_in_menu

  .form-actions
    = f.button :submit
    = link_to t('.cancel', :default => t("helpers.links.cancel")),
                @page.persisted? ? admin_page_path(@page) : admin_pages_path,
                :class => 'btn'

app/views/admin/pages/edit.html.slim
div.page-header
  h1 Editing admin_page

== render 'form'

= link_to 'Show', @page, :class => "btn"
'&nbsp;
= link_to 'Back', admin_pages_path, :class => "btn"

app/views/admin/pages/index.html.slim
div.page-header
  h1 Listing pages

ol.sortable_tree data={max_levels: 5, rebuild_url: rebuild_admin_pages_path}
  = sortable_tree @pages

br

= link_to 'New Page', new_admin_page_path, class: "btn"

app/views/admin/pages/new.html.slim
div.page-header
  h1 New admin_page

== render 'form'

= link_to 'Back', admin_pages_path, :class => "btn"

app/views/admin/pages/show.html.slim
table.table.table-bordered
  tr
    td
      strong Name:
    td
      = @page.name
  tr
    td
      strong Title:
    td
      = @page.title
  tr
    td
      strong Body:
    td
      = @page.body
  tr
    td
      strong Show in menu:
    td
      = @page.show_in_menu

= link_to 'Edit', edit_admin_page_path(@page), :class => "btn"
'&nbsp;
= link_to 'Back', admin_pages_path, :class => "btn"