config/routes.rb
YACMS::Application.routes.draw do
  namespace :admin do
    resources :pages do
      collection do
        post :rebuild
        post :add_image
        post :add_file
        post :add_snippet
      end
    end
    resources :posts do
      collection do
        post :add_image
        post :add_file
        post :add_snippet
      end
    end
    resources :images, except: :show
    resources :attachments, except: :show
    resources :snippets
    resources :users, except: [:show, :new, :create]
    resources :settings, only: [:edit, :update]
  end

  resources :pages, only: [:show]
  resources :posts, only: [:index, :show] do
    resources :comments, only: [:new, :create]
  end

  devise_for :users

  root to: 'pages#home'
end

app/models/attachment.rb
class Attachment < ActiveRecord::Base
  dragonfly_accessor :file

  has_and_belongs_to_many :posts
  has_and_belongs_to_many :pages

  after_update :update_dependent_materials

  def update_dependent_materials
    posts.each(&:regenerate_files!)
    pages.each(&:regenerate_files!)
  end
end

app/controllers/admin/attachments_controller.rb
class Admin::AttachmentsController < Admin::AdminController
  load_resource :attachment
  authorize_resource :attachment

  def create
    if @attachment.save
      redirect_to admin_attachments_path,  notice: "File was successfully created."
    else
      render action: "new"
    end
  end

  def update
    if @attachment.update(attachment_params)
      redirect_to admin_attachments_path, notice: "File was successfully updated."
    else
      render action: "edit"
    end
  end

  def destroy
    @attachment.destroy

    redirect_to admin_attachments_url, notice: "File was successfully deleted."
  end

  protected

  def attachment_params
    params.require(:attachment).permit(:name, :file)
  end

  # Capture any access violations, ensure User isn't unnessisarily redirected to root
  rescue_from CanCan::AccessDenied do |exception|
    if params[:action] == 'index'
      redirect_to root_url, :alert => exception.message
    else
      redirect_to admin_attachments_url, :alert => exception.message
    end
  end
end

app/helpers/admin/attachments_helper.rb
module Admin::AttachmentsHelper

  # Returns the form arguments required to create or update the attachment
  def attachment_form_values(attachment)
    [:admin, attachment]
  end

end

app/views/admin/attachments/_form.html.slim
= simple_form_for(attachment_form_values(@attachment), :html => { class: 'form-horizontal' }) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.file_field :file

  .form-actions
    = f.button :submit, value: 'Create File'

app/views/admin/attachments/edit.html.slim
div.page-header
  h1 Edit file

== render 'form'

= link_to 'Back', admin_attachments_path, :class => "btn"

app/views/admin/attachments/index.html.slim
div.page-header
  h1 Listing files

table.table.table-bordered.table-striped
  thead
    tr
      th Name
      th File
      th style="width: 140px;"
  tbody
  - @attachments.each do |attachment|
    tr
      td = attachment.name
      td = attachment.file.name
      td
        = link_to 'Edit', edit_admin_attachment_path(attachment), :class => "btn btn-mini btn-success"
        | &nbsp;
        = link_to 'Destroy', admin_attachment_path(attachment), :confirm => 'Are you sure?', :method => :delete, :class => "btn btn-mini btn-danger"

br

= link_to 'New File', new_admin_attachment_path, class: "btn"

app/views/admin/attachments/new.html.slim
div.page-header
  h1 New file

== render 'form'

= link_to 'Back', admin_attachments_path, :class => "btn"