config/routes.rb
YACMS::Application.routes.draw do
  namespace :admin do
    resources :pages do
      collection do
        post :rebuild
        post :add_image
        post :add_file
        post :add_snippet
      end
    end
    resources :posts do
      collection do
        post :add_image
        post :add_file
        post :add_snippet
      end
    end
    resources :images, except: :show
    resources :attachments, except: :show
    resources :snippets
    resources :users, except: [:show, :new, :create]
    resources :settings, only: [:edit, :update]
  end

  resources :pages, only: [:show]
  resources :posts, only: [:index, :show] do
    resources :comments, only: [:new, :create]
  end

  devise_for :users

  root to: 'pages#home'
end

app/models/snippet.rb
class Snippet < ActiveRecord::Base
  has_and_belongs_to_many :posts
  has_and_belongs_to_many :pages

  after_update :update_dependent_materials

  def render_content
    res = content.dup
    content.scan(/({{(.*)}})/).each do |substition|
      name = substition[1]
      child_snippet = self.class.where(name: name).first
      if child_snippet
        res.gsub!(substition.first, child_snippet.render_content)
      end
    end
    res
  end

  def update_dependent_materials
    posts.each(&:regenerate_snippets!)
    pages.each(&:regenerate_snippets!)
  end
end

app/controllers/admin/snippets_controller.rb
class Admin::SnippetsController < Admin::AdminController
  load_resource :snippet
  authorize_resource :snippet

  def create
    if @snippet.save
      redirect_to admin_snippet_path(@snippet),  notice: "Snippet was successfully created."
    else
      render action: "new"
    end
  end

  def update
    if @snippet.update(snippet_params)
      redirect_to admin_snippet_path(@snippet), notice: "Snippet was successfully updated."
    else
      render action: "edit"
    end
  end

  def destroy
    @snippet.destroy

    redirect_to admin_snippets_url, notice: "Snippet was successfully deleted."
  end

  protected

  def snippet_params
    params.require(:snippet).permit(:name, :content)
  end

  # Capture any access violations, ensure User isn't unnessisarily redirected to root
  rescue_from CanCan::AccessDenied do |exception|
    if params[:action] == 'index'
      redirect_to root_url, :alert => exception.message
    else
      redirect_to admin_snippets_url, :alert => exception.message
    end
  end
end

app/helpers/admin/snippets_helper.rb
module Admin::SnippetsHelper

  # Returns the form arguments required to create or update the snippet
  def snippet_form_values(snippet)
    [:admin, snippet]
  end

end

app/views/admin/snippets/_form.html.slim
= simple_form_for(snippet_form_values(@snippet), :html => { class: 'form-horizontal' }) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :content

  .form-actions
    = f.button :submit
    = link_to t('.cancel', :default => t("helpers.links.cancel")),
                @snippet.persisted? ? admin_snippet_path(@snippet) : admin_snippets_path,
                :class => 'btn'

app/views/admin/snippets/edit.html.slim
div.page-header
  h1 Editing snippet

== render 'form'

= link_to 'Show', admin_snippet_path(@snippet), :class => "btn"
'&nbsp;
= link_to 'Back', admin_snippets_path, :class => "btn"

app/views/admin/snippets/index.html.slim
div.page-header
  h1 Listing snippets

table.table.table-bordered.table-striped
  thead
    tr
      th Name
      th Content
      th style="width: 140px;"
  tbody
  - @snippets.each do |snippet|
    tr
      td = snippet.name
      td = snippet.content
      td
        = link_to 'Show', admin_snippet_path(snippet), :class => "btn btn-mini btn-info"
        | &nbsp;
        = link_to 'Edit', edit_admin_snippet_path(snippet), :class => "btn btn-mini btn-success"
        | &nbsp;
        = link_to 'Destroy', admin_snippet_path(snippet), :confirm => 'Are you sure?', :method => :delete, :class => "btn btn-mini btn-danger"

br

= link_to 'New Snippet', new_admin_snippet_path, class: "btn"

app/views/admin/snippets/new.html.slim
div.page-header
  h1 New snippet

== render 'form'

= link_to 'Back', admin_snippets_path, :class => "btn"

app/views/admin/snippets/show.html.slim
table.table.table-bordered
  tr
    td
      strong Name:
    td
      = @snippet.name
  tr
    td
      strong Content:
    td
      = @snippet.content

= link_to 'Edit', edit_admin_snippet_path(@snippet), :class => "btn"
'&nbsp;
= link_to 'Back', admin_snippets_path, :class => "btn"