config/routes.rb
YACMS::Application.routes.draw do
  namespace :admin do
    resources :pages do
      collection do
        post :rebuild
        post :add_image
        post :add_file
        post :add_snippet
      end
    end
    resources :posts do
      collection do
        post :add_image
        post :add_file
        post :add_snippet
      end
    end
    resources :images, except: :show
    resources :attachments, except: :show
    resources :snippets
    resources :users, except: [:show, :new, :create]
    resources :settings, only: [:edit, :update]
  end

  resources :pages, only: [:show]
  resources :posts, only: [:index, :show] do
    resources :comments, only: [:new, :create]
  end

  devise_for :users

  root to: 'pages#home'
end

app/models/image.rb
class Image < ActiveRecord::Base
  dragonfly_accessor :image

  has_and_belongs_to_many :posts
  has_and_belongs_to_many :pages

  after_update :update_dependent_materials

  def update_dependent_materials
    posts.each(&:regenerate_images!)
    pages.each(&:regenerate_images!)
  end
end

app/controllers/admin/images_controller.rb
class Admin::ImagesController < Admin::AdminController
  load_resource :image
  authorize_resource :image

  def create
    if @image.save
      redirect_to admin_images_path,  notice: "Image was successfully created."
    else
      render action: "new"
    end
  end

  def update
    if @image.update(image_params)
      redirect_to admin_images_path, notice: "Image was successfully updated."
    else
      render action: "edit"
    end
  end

  def destroy
    @image.destroy

    redirect_to admin_images_url, notice: "Image was successfully deleted."
  end

  protected

  def image_params
    params.require(:image).permit(:name, :image)
  end

  # Capture any access violations, ensure User isn't unnessisarily redirected to root
  rescue_from CanCan::AccessDenied do |exception|
    if params[:action] == 'index'
      redirect_to root_url, :alert => exception.message
    else
      redirect_to admin_images_url, :alert => exception.message
    end
  end
end

app/helpers/admin/images_helper.rb
module Admin::ImagesHelper

  # Returns the form arguments required to create or update the image
  def image_form_values(image)
    [:admin, image]
  end

end

app/views/admin/images/_form.html.slim
= simple_form_for(image_form_values(@image), :html => { class: 'form-horizontal' }) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.file_field :image

  .form-actions
    = f.button :submit

app/views/admin/images/edit.html.slim
div.page-header
  h1 Edit image

== render 'form'

= link_to 'Back', admin_images_path, :class => "btn"

app/views/admin/images/index.html.slim
div.page-header
  h1 Listing images

table.table.table-bordered.table-striped
  thead
    tr
      th Name
      th Image
      th style="width: 140px;"
  tbody
  - @images.each do |image|
    tr
      td = image.name
      td = image_tag image.image.thumb('500x').url
      td
        = link_to 'Edit', edit_admin_image_path(image), :class => "btn btn-mini btn-success"
        | &nbsp;
        = link_to 'Destroy', admin_image_path(image), :confirm => 'Are you sure?', :method => :delete, :class => "btn btn-mini btn-danger"

br

= link_to 'New Image', new_admin_image_path, class: "btn"

app/views/admin/images/new.html.slim
div.page-header
  h1 New image

== render 'form'

= link_to 'Back', admin_images_path, :class => "btn"